# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c6da70f09e0c5f354b60f6c0cfd9e2e1e77662c698718f04fba3e659e25228b0e1f8cf77e7a748f126b44a7b15b4cd1bbd47f4b74b4f6abaee24af903416c92

test:
  secret_key_base: 746fea9636f8dafec79ca2d0f91365ae832c576745190d2fcac9cc52b2104e546775f19c6216cb92b444cb9f4fc4e420dbb2c56ee3aa909ccae3bbc2ab9d6bc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
